package io.github.celebes.amazonscraper;

public enum Category {
	
	// WOMEN_CLOTHING_DRESSES
	WOMEN_CLOTHING_DRESSES_CASUAL,
	WOMEN_CLOTHING_DRESSES_WORK,
	WOMEN_CLOTHING_DRESSES_COCKTAIL,
	WOMEN_CLOTHING_DRESSES_FORMAL,
	WOMEN_CLOTHING_DRESSES_WEDDING,
	WOMEN_CLOTHING_DRESSES_PROM,
	WOMEN_CLOTHING_DRESSES_CLUB;
	
	// WOMEN_CLOTHING_TOPS_AND_TEES
	
	public static final Category[] WOMEN_CLOTHING_DRESSES_ARRAY = {
		WOMEN_CLOTHING_DRESSES_CASUAL,
		WOMEN_CLOTHING_DRESSES_WORK,
		WOMEN_CLOTHING_DRESSES_COCKTAIL,
		WOMEN_CLOTHING_DRESSES_FORMAL,
		WOMEN_CLOTHING_DRESSES_WEDDING,
		WOMEN_CLOTHING_DRESSES_PROM,
		WOMEN_CLOTHING_DRESSES_CLUB
	};

}
